version: "3.8"
services:
  postgresql:
    container_name: "db-phew-api"
    hostname: "host-db-phew"
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - 5432:5432

  node:
    container_name: "api-phew-api"
    hostname: "host-api-phew"
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/data/db
      - PGTZ=GMT
    volumes:
      - .:/home/node/app
    depends_on:
      - postgresql
    ports:
      - 3001:3001
